# body
name: Kirill Ryzhov
bio: Quantitative Consultant

# summary info
description:  Quantitative Consulting

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://drive.google.com/file/d/1JzMVXqLEF83DCbyQWGnlNV8y8gis4eGJ/
url: http://kryzhov.github.io

permalink: /:title/

#markdown: kramdown
#highlighter: rouge

analytics-google: UA-121633993-1

# Futureproof for piwik tracking
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
email: kryzhov@pm.me
phone: +447776154072
linkedin: kryzhov
# youtube: myyoutube
# spotify: myspotify
github: kryzhov
# lastfm: mylastfm
# gitlab: mygitlab
# stackoverflow:
# quora: userquora
# reddit: username
# medium: ryzhov
# vimeo: myvimeo
# lanyrd: mylanyrd


plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

authors:
    kirill:
        name: Kirill Ryzhov
        bio: Quantitative Consultant
        external-image: false
        picture: assets/images/profile.jpg
        linkedin: kryzhov

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true
personal: true

# do you want to show the "read time" of the posts?
read-time: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?  
show-author: true

# do you want some animations?
animation: true
